project:
  type: website
  output-dir: docs

website:
  title: "Anoob Prakash"
  description: "The lab website of Stephen R. Keller"
  image: img/AP_logo.png
  favicon: img/AP_logo.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/AP_logo.png
    
    # your sub-pages
    left:
      - text: "Research"
        href: research/research.qmd
      - text: "Publications"
        href: publications/publications.qmd
      - text: "Photos"
        href: photos/photos.qmd
      
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/anoob-prakash/
      - icon: google
        href: https://scholar.google.com/citations?hl=en&user=jIOSRMkAAAAJ
      - icon: github
        href: https://github.com/anoobvinu07
      - icon: envelope
        aria-label: email
        href: "mailto:anoobvinu@gmail.com"
        
  # person-workspace
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">
      Â© Copyright <span id="year"></span> | Anoob Prakash
      </span>
      <script>
        document.getElementById("year").textContent = new Date().getFullYear();
      </script>
 
format:
  html:
    fontsize: 1.1em
    theme: 
      # - litera
      - style2.scss
    toc: true
    toc-depth: 4
    toc-title: ""
    footnotes-hover: true
    highlight-style: tango